/* Compact post-trip ledger data. It intentionally does not duplicate itinerary copy. */
(function exposeIcelandBillData() {
  window.IcelandBillData = {
    version: "1",
    title: "建皇结算版",
    subtitle: "只统计建皇组合已付款项；共同费用的个人应摊另行标注。",
    currencies: {
      CNY: { label: "人民币", symbol: "¥", decimals: 2 },
      EUR: { label: "欧元", symbol: "€", decimals: 2 },
      ISK: { label: "冰岛克朗", symbol: "ISK ", decimals: 0 },
    },
    expenses: [
      {
        id: "lodging-lisbon",
        date: "09/25–09/27",
        dateKey: "09/25",
        category: "住宿",
        title: "里斯本 The Delight Hostel",
        amount: 1787.44,
        currency: "CNY",
        shareAmount: 893.72,
        shareCurrency: "CNY",
        status: "confirmed",
        split: "建皇 2/4 人，共 2 晚",
        note: "订单总额按 4 人、2 晚分摊；建皇两人的可计算应摊为 ¥893.72。",
        anchor: "day-jianhuang-09-25",
      },
      {
        id: "lodging-porto",
        date: "09/27–09/28",
        dateKey: "09/27",
        category: "住宿",
        title: "波尔图盖亚美居酒店",
        amount: 544.94,
        currency: "CNY",
        shareAmount: 363.29,
        shareCurrency: "CNY",
        status: "confirmed",
        split: "建皇 2/3 人，共 1 晚",
        note: "订单总额按建皇两人和龙龙共 3 人分摊；四舍五入到分。",
        anchor: "day-jianhuang-09-27",
      },
      {
        id: "lodging-reykjavik-early",
        date: "09/29–10/03",
        dateKey: "09/29",
        category: "住宿",
        title: "雷克雅未克 Fosshotel Lind（前段）",
        amount: 4804.42,
        currency: "CNY",
        shareAmount: 4804.42,
        shareCurrency: "CNY",
        status: "confirmed",
        split: "2 人订单，共 4 晚",
        note: "建皇提前段住宿；住宿总表记录金额 ¥4804.42。",
        anchor: "day-jianhuang-09-29",
      },
      {
        id: "lodging-reykjavik-oct03",
        date: "10/03–10/04",
        dateKey: "10/03",
        category: "住宿",
        title: "雷克雅未克 Fosshotel Lind（10/03）",
        amount: 1287.49,
        currency: "CNY",
        shareAmount: null,
        shareCurrency: "CNY",
        status: "needs-confirmation",
        split: "2 人订单，共 1 晚",
        note: "住宿总表按预付 ¥3169.83 减退款 ¥1882.34 记录实际支付 ¥1287.49；付款人和建皇归属仍待原始凭证确认。",
        anchor: "day-jianhuang-10-03",
      },
      {
        id: "lodging-reykjavik-oct05",
        date: "10/05–10/06",
        dateKey: "10/05",
        category: "住宿",
        title: "雷克雅未克 Fosshotel Lind（10/05）",
        amount: 988.61,
        currency: "CNY",
        shareAmount: 988.61,
        shareCurrency: "CNY",
        status: "confirmed",
        split: "2 人订单，共 1 晚",
        note: "南岸团回城后入住；住宿总表记录金额 ¥988.61。",
        anchor: "day-jianhuang-10-05",
      },
      {
        id: "storage-paris",
        date: "09/28",
        dateKey: "09/28",
        category: "行李寄存",
        title: "LOCK & enjoy! 巴黎东站店",
        amount: 16.9,
        currency: "EUR",
        shareAmount: 16.9,
        shareCurrency: "EUR",
        status: "confirmed",
        split: "建皇组合共同使用",
        note: "M+ 型 18 号柜；订单时段 09/28 13:00–09/29 04:00。",
        anchor: "day-jianhuang-09-28",
      },
      {
        id: "tour-silfra",
        date: "09/29",
        dateKey: "09/29",
        category: "团费",
        title: "史费拉裂缝浮潜",
        amount: 2585.04,
        currency: "CNY",
        shareAmount: 2585.04,
        shareCurrency: "CNY",
        status: "confirmed",
        split: "2 人订单",
        note: "含雷克雅未克接送。",
        anchor: "day-jianhuang-09-29",
      },
      {
        id: "tour-kerlingarfjoll",
        date: "09/30",
        dateKey: "09/30",
        category: "团费",
        title: "Kerlingarfjöll 高地徒步（原团）",
        amount: 2568.57,
        currency: "CNY",
        shareAmount: null,
        shareCurrency: "CNY",
        status: "refunded",
        split: "原团已取消，100% 退款",
        note: "原 Kerlingarfjöll 高地徒步团已取消并全额退款；这笔原订单金额不计入建皇账单合计。",
        anchor: "day-jianhuang-09-30",
      },
      {
        id: "tour-reykjanes-volcanic",
        date: "09/30",
        dateKey: "09/30",
        category: "团费",
        title: "Hike to Volcanic Eruption Sites & Reykjanes Tour",
        amount: 1670.53,
        currency: "CNY",
        shareAmount: 1670.53,
        shareCurrency: "CNY",
        status: "confirmed",
        split: "2 人订单",
        note: "BusTravel Iceland；08:00 开始接车，接车窗口可持续至 08:30；Bus Stop 13，Rauðarárstígur（Laugavegur 120）。",
        anchor: "day-jianhuang-09-30",
      },
      {
        id: "tour-snaefellsnes",
        date: "10/01",
        dateKey: "10/01",
        category: "团费",
        title: "斯奈山半岛小团",
        amount: 1796,
        currency: "CNY",
        shareAmount: 1796,
        shareCurrency: "CNY",
        status: "confirmed",
        split: "2 人订单",
        note: "攻略同时记录 ¥898/人。",
        anchor: "day-jianhuang-10-01",
      },
      {
        id: "tour-landmannalaugar",
        date: "10/02",
        dateKey: "10/02",
        category: "团费",
        title: "兰德曼那劳卡高地超级吉普",
        amount: 3260.37,
        currency: "CNY",
        shareAmount: 3260.37,
        shareCurrency: "CNY",
        status: "confirmed",
        split: "2 人订单",
        note: "08:00 在 Klettur Hótel 等车。",
        anchor: "day-jianhuang-10-02",
      },
      {
        id: "tour-golden-circle",
        date: "10/03",
        dateKey: "10/03",
        category: "团费",
        title: "黄金圈下午团",
        amount: 691.31,
        currency: "CNY",
        shareAmount: null,
        shareCurrency: "CNY",
        status: "confirmed",
        shareStatus: "needs-confirmation",
        split: "攻略一处写 1 人，另一处写 ¥691.31/人",
        note: "总付款先记录为 ¥691.31；建皇应按 1 人还是 2 人计入，需对照原始订单确认。",
        anchor: "day-jianhuang-10-03",
      },
      {
        id: "tour-south-coast",
        date: "10/04–10/05",
        dateKey: "10/04",
        category: "团费",
        title: "南岸两日 + 蓝冰洞",
        amount: 509400,
        currency: "ISK",
        shareAmount: 145542.86,
        shareCurrency: "ISK",
        status: "confirmed",
        split: "总额 7 人；建皇 2/7 为暂估",
        shareStatus: "estimate",
        note: "订单总额已全额支付；建皇两人份额按 2/7 均摊估算，实际以你们结算约定为准。",
        anchor: "day-jianhuang-10-04",
      },
      {
        id: "tour-sky-lagoon",
        date: "10/06",
        dateKey: "10/06",
        category: "门票",
        title: "Sky Lagoon 温泉",
        amount: 1441.87,
        currency: "CNY",
        shareAmount: 1441.87,
        shareCurrency: "CNY",
        status: "confirmed",
        split: "2 人订单",
        note: "13:00 入场；不含接送。",
        anchor: "day-jianhuang-10-06",
      },
      {
        id: "lodging-copenhagen",
        date: "10/07–10/08",
        dateKey: "10/07",
        category: "住宿",
        title: "哥本哈根 Cabinn Metro Hotel",
        amount: 547.72,
        currency: "CNY",
        shareAmount: 547.72,
        shareCurrency: "CNY",
        status: "confirmed",
        split: "2 人订单",
        note: "Arne Jacobsens Allé 2；住宿总表记录为 ¥273.86/人。",
        anchor: "day-jianhuang-10-07",
      },
      {
        id: "flight-europe",
        date: "09/25–10/08",
        dateKey: "09/25",
        category: "交通",
        title: "欧洲及冰岛往返机票",
        amount: null,
        currency: "CNY",
        shareAmount: null,
        shareCurrency: "CNY",
        status: "missing",
        split: "待补实际付款凭证",
        note: "行程已记录航班，但当前攻略未记录票价；不做估算。",
        anchor: "day-jianhuang-09-25",
      },
      {
        id: "bus-lisbon-porto",
        date: "09/27",
        dateKey: "09/27",
        category: "交通",
        title: "里斯本 → 波尔图 FlixBus",
        amount: null,
        currency: "CNY",
        shareAmount: null,
        shareCurrency: "CNY",
        status: "missing",
        split: "待补车票金额",
        note: "龙龙单独购票；建皇组合的票价未写入攻略。",
        anchor: "day-jianhuang-09-27",
      },
      {
        id: "tickets-sintra",
        date: "09/26",
        dateKey: "09/26",
        category: "门票",
        title: "雷加莱拉庄园 + 佩纳公园门票",
        amount: null,
        currency: "CNY",
        shareAmount: null,
        shareCurrency: "CNY",
        status: "missing",
        split: "待补 4 张票实际金额",
        note: "攻略确认已购 4 张票，但当前页面没有记录票价。",
        anchor: "day-jianhuang-09-26",
      },
      {
        id: "dining-lisbon",
        date: "09/25–09/26",
        dateKey: "09/25",
        category: "餐饮",
        title: "里斯本已订餐厅与一日游午餐",
        amount: null,
        currency: "CNY",
        shareAmount: null,
        shareCurrency: "CNY",
        status: "missing",
        split: "待补餐饮实际付款",
        note: "包含 Alfama8848、海边午餐备选和 Frade Dos Mares。",
        anchor: "day-jianhuang-09-26",
      },
      {
        id: "dining-porto-paris",
        date: "09/27–09/28",
        dateKey: "09/27",
        category: "餐饮",
        title: "波尔图与巴黎已订餐厅",
        amount: null,
        currency: "CNY",
        shareAmount: null,
        shareCurrency: "CNY",
        status: "missing",
        split: "待补餐饮实际付款",
        note: "包含 Meia-Nau、Brasão、Carré Pain de Mie、Bouillon Julien 和 Al Caratello。",
        anchor: "day-jianhuang-09-27",
      },
      {
        id: "dining-caruso",
        date: "10/05",
        dateKey: "10/05",
        category: "餐饮",
        title: "Caruso 晚餐（7 人）",
        amount: null,
        currency: "ISK",
        shareAmount: null,
        shareCurrency: "ISK",
        status: "missing",
        split: "待补餐厅账单",
        note: "预订确认码已在攻略中记录；金额和实际付款人未记录。",
        anchor: "day-jianhuang-10-05",
      },
      {
        id: "local-transport",
        date: "09/25–10/08",
        dateKey: "09/28",
        category: "交通",
        title: "机场、公交、地铁与市内转场",
        amount: null,
        currency: "CNY",
        shareAmount: null,
        shareCurrency: "CNY",
        status: "missing",
        split: "待补交通流水",
        note: "不根据路线距离估算；可在下方添加一笔实际支出。",
        anchor: "day-jianhuang-09-28",
      },
    ],
    itinerary: [
      ["09/25", "抵达里斯本 + 四人住宿", "day-jianhuang-09-25"],
      ["09/26", "里斯本郊区海边一日游", "day-jianhuang-09-26"],
      ["09/27", "里斯本 → 波尔图", "day-jianhuang-09-27"],
      ["09/28", "巴黎寄存 + 夜游", "day-jianhuang-09-28"],
      ["09/29", "史费拉浮潜", "day-jianhuang-09-29"],
      ["09/30", "雷克雅内斯火山地貌团", "day-jianhuang-09-30"],
      ["10/01", "斯奈山半岛小团", "day-jianhuang-10-01"],
      ["10/02", "兰德曼那劳卡高地超级吉普", "day-jianhuang-10-02"],
      ["10/03", "黄金圈下午团", "day-jianhuang-10-03"],
      ["10/04", "南岸两日团第一天", "day-jianhuang-10-04"],
      ["10/05", "蓝冰洞 + Caruso", "day-jianhuang-10-05"],
      ["10/06", "Sky Lagoon + 飞米兰", "day-jianhuang-10-06"],
      ["10/07", "米兰 → 里斯本 → 哥本哈根", "day-jianhuang-10-07"],
      ["10/08", "哥本哈根转机 + 回北京", "day-jianhuang-10-08"],
    ],
  };
})();
