const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { execFileSync } = require('node:child_process');
const root = path.resolve(__dirname, '..');
execFileSync(process.execPath, [path.join(__dirname, 'build-travel-backup.cjs')], { cwd: root, stdio: 'inherit' });
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const swPath = path.join(root, 'sw.js');
const swRelease = /\n\/\/ offline release [a-f0-9]{12}\n?$/;
const swSource = fs.readFileSync(swPath, 'utf8').replace(swRelease, '\n');
const core = ['index.html', 'travel-backup.html', ...Array.from(html.matchAll(/(?:src|href)="([^"?]+\.(?:js|css)(?:\?[^\"]*)?)"/g), (match) => match[1])];
function walk(directory) {
  return fs.readdirSync(path.join(root, directory), { withFileTypes: true }).flatMap((entry) => {
    const name = `${directory}/${entry.name}`;
    return entry.isDirectory() ? walk(name) : [name];
  });
}
const media = walk('assets').filter((name) => /\.(webp|png|jpg|svg)$/i.test(name)).sort();
const hash = crypto.createHash('sha256');
const mediaHash = crypto.createHash('sha256');
const integrity = {};
for (const name of [...core, ...media]) {
  const contents = fs.readFileSync(path.join(root, name.split('?')[0]));
  hash.update(name);
  hash.update(contents);
  if (core.includes(name)) integrity[name] = `sha256-${crypto.createHash('sha256').update(contents).digest('base64')}`;
  if (media.includes(name)) mediaHash.update(name).update(contents);
}
hash.update('sw.js');
hash.update(swSource);
const manifest = { version: hash.digest('hex').slice(0, 12), mediaVersion: mediaHash.digest('hex').slice(0, 12), core, media, integrity };
fs.writeFileSync(swPath, `${swSource.trimEnd()}\n// offline release ${manifest.version}\n`);
fs.writeFileSync(path.join(root, 'offline-assets.js'), `// Generated by node scripts/build-offline.cjs; update after every site change.\nself.TRAVEL_OFFLINE_MANIFEST = ${JSON.stringify(manifest, null, 2)};\n`);
console.log(`Offline version ${manifest.version}: ${core.length} core files, ${media.length} images.`);
